import { NextResponse } from 'next/server';
import { generateAndValidate } from '@archivox/generator';
import { generateAutoCadScr, generateFloorPlanSvg } from '@archivox/engines';

export async function POST(req: Request) {
  const body = await req.json().catch(() => ({}));
  const prompt = String(body?.prompt ?? '').slice(0, 2000);

  if (!prompt.trim()) {
    return NextResponse.json({ error: 'Missing prompt' }, { status: 400 });
  }

  const { layout, validation, attempts } = generateAndValidate(
    { prompt },
    { scoreThreshold: 70, maxAttempts: 4 }
  );

  const { svg } = generateFloorPlanSvg(layout);
  const { script } = generateAutoCadScr(layout);

  return NextResponse.json({
    prompt,
    layout,
    svg,
    script,
    validation,
    meta: {
      attempts,
      notes: [
        'MVP: layout generated by a deterministic heuristic (no model cost).',
        'Next: replace the generator with an LLM planner.',
      ],
    },
  });
}
