import { NextResponse } from 'next/server';
import { generateLayoutFromText } from '@archivox/generator';
import { generateAutoCadScr, generateFloorPlanSvg } from '@archivox/engines';

export async function POST(req: Request) {
  const body = await req.json().catch(() => ({}));
  const prompt = String(body?.prompt ?? '').slice(0, 2000);

  if (!prompt.trim()) {
    return NextResponse.json({ error: 'Missing prompt' }, { status: 400 });
  }

  const layout = generateLayoutFromText({ prompt });
  const { svg } = generateFloorPlanSvg(layout);
  const { script } = generateAutoCadScr(layout);

  return NextResponse.json({
    prompt,
    layout,
    svg,
    script,
    notes: [
      'MVP: This layout is generated by a deterministic heuristic (no model cost).',
      'Next: replace the generator with an LLM planner and add validation + adjacency constraints.'
    ]
  });
}
